# Generated by Django 4.0.4 on 2022-04-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_slug_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
    ]
