# Generated by Django 4.0.4 on 2022-04-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_task_assignee_alter_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimate',
            field=models.FloatField(default=0, null=True),
        ),
    ]
