# Generated by Django 4.0.4 on 2022-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_task_assignee_alter_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tracked_time',
            field=models.IntegerField(null=True),
        ),
    ]
