# Generated by Django 4.0.4 on 2022-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_task_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tracked_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
